### ISSUE TITLE
Speed up instance proofs of `Primitives`

### ISSUE THREAD

**Issue by Columbus240** [mit-plv/riscv-coq#14]
Proofs in `Minimal.v`, `MinimalMMIO.v` and `MetricMinimalMMIO.v` are very slow (ordered from a little slow to very slow) and make it annoying to check whether some changes are consistent with the rest of the code.
Maybe the amount of backtracking that has to be done can be reduced. The proofs use similar code of Ltac that maybe can be put in one place (Utility/Tactics.v might be good). Separating the tactics that do a lot of backtracking like `_  |- _ \/ _ => left` from the ones that do very little or no backtracking might be a good idea, if it is reasonably possible. Maybe CPDT of Chlipala has some ideas.

**Comment by samuelgruetter** [comment]
You're right, these proofs should definitely be improved. One way would be to make the tactic `t` better/more general, but probably it would be better to define `MinimalMMIO` in terms of `Minimal`, and `MetrictMinimalMMIO` in terms of `MinimalMMIO`, and then each additional layer would only have to prove what it adds instead of the whole thing. I tried to do that about 2 times already and gave up each time because I ran out of the time I had allocated for that, and after all, it works as it is, and the ugliness is hidden behind a reasonable interface (`riscv.Spec.Primitives`).

But if you find a way to improve this, that'd be more than welcome!

**Comment by samuelgruetter** [comment]
While adding a parametrizable `ext_spec` to the instances, I also made some improvements regarding this issue:
* In https://github.com/mit-plv/riscv-coq/commit/1175fb12e499a9d16002d17791fbd5650928a851, I changed the instance proof of `MinimalMMIO` to do less unfolding and use more helper lemmas instead.
* In https://github.com/mit-plv/riscv-coq/commit/674cff5c37b77950acd630b59cafea06b16cb667, I reused instance proofs from `MinimalMMIO` for the instance proof of `MetricMinimalMMIO`.

**Comment by Columbus240** [comment]
Thanks. `MetricMinimalMMIO` still takes about 45s to compile for me, but I think it’s faster now (didn’t measure it earlier).

**Comment by samuelgruetter** [comment]
On Coq's CI, which runs with timing enabled, it went down from [829 seconds](https://gitlab.com/coq/coq/-/jobs/205046185) to [71 seconds](https://gitlab.com/coq/coq/-/jobs/207767504). Feel free to suggest a PR which improves it further :wink:

**Comment by Columbus240** [comment]
Just wow!
I had a look at it using the profiler and didn’t find a (simple) opportunity to optimize it further.
